# Copyright 2025 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Corne 36 ZMK Studio'
on: workflow_dispatch
jobs:
  build-left:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left nice_view_adapter nice_view"]'
      kconfig: '["CONFIG_ZMK_STUDIO=y\nCONFIG_ZMK_STUDIO_LOCKING=n\nCONFIG_ZMK_POINTING=y"]'
      snippet: '["studio-rpc-usb-uart"]'
  build-right:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_right nice_view_adapter nice_view"]'
      kconfig: '["CONFIG_ZMK_POINTING=y"]'
